-- ini untuk keperluan initialisasi kategori dan soal
INSERT INTO `categories` (`name`, `target`) VALUES
('Pedagogik', 'Penilai'),
('Kepribadian', 'Penilai'),
('Sosial', 'Penilai'),
('Profesional', 'Penilai'),
('Kedisiplinan', 'Penilai'),
('Loyalitas Dan Tanggung Jawab', 'Penilai');

INSERT INTO `categories` (`name`, `target`) VALUES
('Prilaku Guru sehari-hari', 'Teman Sejawat'),
('Hubungan Guru dengan Teman Sejawat', 'Teman Sejawat'),
('Prilaku Profesional Guru', 'Teman Sejawat');

INSERT INTO `categories` (`name`, `target`) VALUES
('Komunikasi', 'Orang Tua'),
('Kepercayaan dalam memberikan pendidikan kepada peserta didik', 'Orang Tua');

INSERT INTO `categories` (`name`, `target`) VALUES
('Penguasaan Materi', 'Siswa'),
('Kemahiran dalam Mengajar', 'Siswa'),
('Perilaku Profesional Guru ', 'Siswa'),
('Hubungan Sosial dengan Peserta Didik', 'Siswa');

INSERT INTO `categories` (`parent_id`,`name`,`target`) VALUES 
(1, 'Menguasai karakteristik peserta didik','Penilai'),
(1, 'Menguasai teori belajar dan prinsip-prinsip pembelajaran yang mendidik','Penilai'),
(1, 'Pengembangan kurikulum','Penilai'),
(1, 'Kegiatan pembelajaran yang mendidik','Penilai'),
(1, 'Pengembangan potensi peserta didik','Penilai'),
(1, 'Komunikasi dengan peserta didik','Penilai'),
(1, 'Penilaian dan evaluasi','Penilai'),
(2, 'Bertindak sesuai dengan norma agama, hukum, sosial dan kebudayaan Nasional','Penilai'),
(2, 'Menunjukkan pribadi yang dewasa dan teladan','Penilai'),
(2, 'Etos kerja, tanggung jawab yang tinggi, rasa bangga menjadi guru','Penilai'),
(3, 'Bersikap inklusif, bertindak obyektif, serta tidak diskriminatif','Penilai'),
(3, 'Komunikasi dengan sesama guru, tenaga kependidikan, orang tua, peserta didik, dan masyarakat','Penilai'),
(4, 'Penguasaan materi, struktur, konsep dan pola pikir keilmuan yang mendukung mata pelajaran yang diampu','Penilai'),
(4, 'Mengembangkan keprofesionalan melalui tindakan yang reflektif','Penilai'),
(5, 'Taat Terhadap kebijakan yang Berlaku Di Sekolah','Penilai'),
(6, 'Bersikap Loyal terhadap lembaga dan memiliki integritas dalam bertugas','Penilai');

INSERT INTO `questions` (`categorie_id`,`description`) VALUES
(16, 'Guru dapat mengidentifikasi karakteristik belajarsetiap peserta didik di kelasnya.'),
(16, 'Guru  memastikan  bahwa  semua  peserta  didik mendapatkan  kesempatan  yang  sama  untuk berpartisipasi  aktif  dalam  kegiatan  pembelajaran.'),
(16, 'Guru  dapat  mengatur  kelas  untuk  memberikan kesempatan  belajar  yang  sama  pada  semua peserta  didik  dengan  kelainan  fisik  dan kemampuan  belajar  yang  berbeda.'),
(16, 'Guru  mencoba  mengetahui  penyebab penyimpangan  perilaku  peserta  didik  untuk mencegah  agar  perilaku  tersebut  tidak  merugikan peserta  didik  lainnya.'),
(16, 'Guru  membantu  mengembangkan  potensi  dan mengatasi  kekurangan  peserta  didik.'),
(16, 'Guru  memperhatikan  peserta  didik  dengan kelemahan  fisik  tertentu  agar  dapat  mengikuti aktivitas  pembelajaran,  sehingga  peserta  didik tersebut  tidak  termarginalkan  (tersisihkan,  diolok‐olok,  minder,  dsb.).'),
(17, 'Guru  memberi  kesempatan  kepada  peserta  didik untuk  menguasai  materi  pembelajaran  sesuai  usia dan  kemampuan  belajarnya  melalui  pengaturan proses  pembelajaran  dan  aktivitas  yang  bervariasi.'),
(17, 'Guru  selalu  memastikan  tingkat  pemahaman  peserta didik  terhadap  materi  pembelajaran  tertentu  dan menyesuaikan  aktivitas  pembelajaran  berikutnya berdasarkan  tingkat  pemahaman  tersebut.'),
(17, 'Guru  dapat  menjelaskan  alasan  pelaksanaan kegiatan/aktivitas  yang  dilakukannya,  baik  yang sesuai  maupun  yang  berbeda  dengan  rencana, terkait  keberhasilan  pembelajaran.'),
(17, 'Guru  menggunakan  berbagai  teknik  untuk memotiviasi  kemauan  belajar  peserta  didik.'),
(17, 'Guru  merencanakan  kegiatan  pembelajaran  yang saling  terkait  satu  sama  lain,  dengan  memperhatikan tujuan  pembelajaran  maupun  proses  belajar  peserta didik.'),
(17, 'Guru  memperhatikan  respon  peserta  didik  yang belum/kurang  memahami  materi  pembelajaran  yang diajarkan  dan  menggunakannya  untuk  memperbaiki rancangan  pembelajaran  berikutnya.'),
(18, 'Guru  dapat  menyusun  silabus  yang  sesuai  dengan kurikulum.'),
(18, 'Guru  merancang  rencana  pembelajaran  yang  sesuai dengan  silabus  untuk  membahas  materi  ajar tertentu  agar  peserta  didik  dapat  mencapai kompetensi  dasar  yang  ditetapkan.'),
(18, 'Guru  mengikuti  urutan  materi  pembelajaran dengan  memperhatikan  tujuan  pembelajaran.'),
(18, 'Guru  memilih  materi  pembelajaran  yang:  a)  sesuai dengan  tujuan  pembelajaran,  b)  tepat  dan mutakhir,  c)  sesuai  dengan  usia  dan  tingkat kemampuan  belajar  peserta  didik,  dan  d)  dapat dilaksanakan  di  kelas  e)  sesuai  dengan  konteks kehidupan  sehari‐hari  peserta  didik.'),
(19, 'Guru  melaksanakan  aktivitas  pembelajaran  sesuai  dengan rancangan  yang  telah  disusun  secara  lengkap  dan pelaksanaan  aktivitas  tersebut  mengindikasikan  bahwa  guru mengerti  tentang  tujuannya.'),
(19, 'Guru  melaksanakan  aktivitas  pembelajaran  yang  bertujuan untuk  membantu  proses  belajar  peserta  didik,  bukan  untuk menguji  sehingga  membuat  peserta  didik  merasa  tertekan.'),
(19, 'Guru  mengkomunikasikan  informasi  baru  (misalnya  materi tambahan)  sesuai  dengan  usia  dan  tingkat  kemampuan belajar  peserta  didik.'),
(19, 'Guru  menyikapi  kesalahan  yang  dilakukan  peserta  didik sebagai  tahapan  proses  pembelajaran,  bukan  semata‐mata kesalahan  yang  harus  dikoreksi.  Misalnya:  dengan mengetahui  terlebih  dahulu  peserta  didik  lain  yang  setuju atau  tidak  setuju  dengan  jawaban  tersebut,  sebelum memberikan  penjelasan  tentang  jawaban  yang  benar.'),
(19, 'Guru  melaksanakan  kegiatan  pembelajaran  sesuai  isi kurikulum  dan  mengkaitkannya  dengan  konteks  kehidupan sehari‐hari  peserta  didik.'),
(19, 'Guru  melakukan  aktivitas  pembelajaran  secara  bervariasi dengan  waktu  yang  cukup  untuk  kegiatan  pembelajaran yang  sesuai  dengan  usia  dan  tingkat  kemampuan  belajar  dan mempertahankan  perhatian  peserta  didik.'),
(19, 'Guru  mengelola  kelas  dengan  efektif  tanpa  mendominasi atau  sibuk  dengan  kegiatannya  sendiri  agar  semua  waktu peserta  dapat  termanfaatkan  secara  produktif.'),
(19, 'Guru  mampu  menyesuaikan  aktivitas  pembelajaran  yang dirancang  dengan  kondisi  kelas.'),
(19, 'Guru  memberikan  banyak  kesempatan  kepada  peserta  didik untuk  bertanya,  mempraktekkan  dan  berinteraksi  dengan peserta  didik  lain.'),
(19, 'Guru  mengatur  pelaksanaan  aktivitas  pembelajaran  secara sistematis  untuk  membantu  proses  belajar  peserta  didik. Sebagai  contoh:  guru  menambah  informasi  baru  setelah mengevaluasi  pemahaman  peserta  didik  terhadap  materi sebelumnya.'),
(19, 'Guru  menggunakan  alat  bantu  mengajar,  dan/atau  audio‐visual  (termasuk  TIK)  untuk  meningkatkan  motivasi  belajar peserta  didik  dalam  mencapai  tujuan  pembelajaran.'),
(20, 'Guru  menganalisis  hasil  belajar  berdasarkan segala  bentuk  penilaian  terhadap  setiap  peserta didik  untuk  mengetahui  tingkat  kemajuan  masing‐masing.'),
(20, 'Guru  merancang  dan  melaksanakan  aktivitas pembelajaran  yang  mendorong  peserta  didik untuk  belajar  sesuai  dengan  kecakapan  dan  pola belajar  masing‐masing.'),
(20, 'Guru  merancang  dan  melaksanakan  aktivitas pembelajaran  untuk  memunculkan  daya kreativitas  dan  kemampuan  berfikir  kritis  peserta didik.'),
(20, 'Guru  secara  aktif  membantu  peserta  didik  dalam proses  pembelajaran  dengan  memberikan perhatian  kepada  setiap  individu.'),
(20, 'Guru  dapat  mengidentifikasi  dengan  benar tentang  bakat,  minat,  potensi,  dan  kesulitan belajar  masing-masing  peserta  didik. '),
(20, 'Guru  memberikan  kesempatan  belajar  kepada peserta  didik  sesuai  dengan  cara  belajarnya masing-masing. '),
(20, 'Guru  memdengan  peserta  didik  dan  mendorongnya  untuk memahami  dan  menggunakan  informasi  yang disampaikan. usatkan  perhatian  pada  interaksi '),
(21, 'Guru  menggunakan  pertanyaan  untuk  mengetahui pemahaman  dan  menjaga  partisipasi  peserta  didik, termasuk  memberikan  pertanyaan  terbuka  yang menuntut  peserta  didik  untuk  menjawab  dengan  ide dan  pengetahuan  mereka. '),
(21, 'Guru  memberikan  perhatian  dan  mendengarkan semua  pertanyaan  dan  tanggapan  peserta  didik, tanpa  menginterupsi,  kecuali  jika  diperlukan  untuk membantu  atau  mengklarifikasi pertanyaan/tanggapan  tersebut. '),
(21, 'Guru  menanggapinya  pertanyaan  peserta  didik secara  tepat,  benar,  dan  mutakhir,  sesuai  tujuan pembelajaran  dan  isi  kurikulum,  tanpa mempermalukannya. '),
(21, 'Guru  menyajikan  kegiatan  pembelajaran  yang  dapat menumbuhkan  kerja  sama  yang  baik  antar pesertadidik. '),
(21, 'Guru  mendengarkan  dan  memberikan  perhatian terhadap  semua  jawaban  peserta  didik  baik  yang benar  maupun  yang  dianggap  salah  untuk  mengukur tingkat  pemahaman  peserta  didik. '),
(21, 'Guru  memberikan  perhatian  terhadap  pertanyaan peserta  didik  dan  meresponnya  secara  lengkap  dan relevan  untuk  menghilangkan  kebingungan  pada peserta  didik.'),
(22, 'Guru  menyusun  alat  penilaian  yang  sesuai  dengan tujuan  pembelajaran  untuk  mencapai  kompetensi tertentu  seperti  yang  tertulis  dalam  RPP. '),
(22, 'Guru  melaksanakan  penilaian  dengan  berbagai teknik  dan  jenis  penilaian,  selain  penilaian  formal yang  dilaksanakan  sekolah,  dan  mengumumkan hasil  serta  implikasinya  kepada  peserta  didik, tentang  tingkat  pemahaman  terhadap  materi pembelajaran  yang  telah  dan  akan  dipelajari. '),
(22, 'Guru  menganalisis  hasil  penilaian  untuk mengidentifikasi  topik/kompetensi  dasar  yang  sulit sehingga  diketahui  kekuatan  dan  kelemahan masing‐masing  peserta  didik  untuk  keperluan remedial  dan  pengayaan. '),
(22, 'Guru  memanfaatkan  masukan  dari  peserta  didik dan  merefleksikannya  untuk  meningkatkan pembelajaran  selanjutnya,  dan  dapat membuktikannya  melalui  catatan,  jurnal pembelajaran,  rancangan  pembelajaran,  materi tambahan,  dan  sebagainya. '),
(22, 'Guru  memanfatkan  hasil  penilaian  sebagai  bahan penyusunan  rancangan  pembelajaran  yang  akan dilakukan  selanjutnya. ');

INSERT INTO `questions` (`categorie_id`,`description`) VALUES
(23, 'Guru menghargai dan mempromosikan prinsip-prinsip Pancasila sebagai dasar  ideologi  dan  etika  bagi  semua warga  Indonesia.'),
(23, 'Guru  mengembangkan  kerjasama  dan  membina kebersamaan  dengan  teman  sejawat  tanpa memperhatikan  perbedaan  yang  ada  (misalnya:  suku, agama,  dan  gender).'),
(23, 'Guru  saling  menghormati  dan  menghargai  teman sejawat  sesuai  dengan  kondisi  dan  keberadaan  masing‐masing. '),
(23, 'Guru  memiliki  rasa  persatuan  dan  kesatuan  sebagai bangsa  Indonesia.'),
(23, 'Guru  mempunyai  pandangan  yang  luas  tentang keberagaman  bangsa  Indonesia  (misalnya:  budaya,  suku, agama). '),
(24, 'Guru  bertingkah  laku  sopan  dalam  berbicara, berpenampilan,  dan  berbuat  terhadap  semua peserta  didik,  orang  tua,  dan  teman  sejawat. '),
(24, 'Guru  mau  membagi  pengalamannya  dengan  teman sejawat,  termasuk  mengundang  mereka  untuk mengobservasi  cara  mengajarnya  dan  memberikan masukan.'),
(24, 'Guru  mampu  mengelola  pembelajaran  yang membuktikan  bahwa  guru  dihormati  oleh  peserta didik,  sehingga  semua  peserta  didik  selalu memperhatikan  guru  dan  berpartisipasi  aktif  dalam proses  pembelajaran. '),
(24, 'Guru  bersikap  dewasa  dalam  menerima  masukan dari  peserta  didik  dan  memberikan  kesempatan kepada  peserta  didik  untuk  berpartisipasi  dalam proses  pembelajaran. '),
(24, 'Guru  berperilaku  baik  untuk  mencitrakan  nama baik  sekolah.'),
(25, 'Guru  mengawali  dan  mengakhiri  pembelajaran dengan  tepat  waktu. '),
(25, 'Jika  guru  harus  meninggalkan  kelas,  guru mengaktifkan  siswa  dengan  melakukan  hal‐hal produktif  terkait  dengan  mata  pelajaran,  dan meminta  guru  piket  atau  guru  lain  untuk mengawasi  kelas. '),
(25, 'Guru  memenuhi  jam  mengajar  dan  dapat melakukan  semua  kegiatan  lain  di  luar  jam mengajar  berdasarkan  ijin  dan  persetujuan pengelola  sekolah. '),
(25, 'Guru  meminta  ijin  dan  memberitahu  lebih  awal, dengan  memberikan  alasan  dan  bukti  yang  sah jika  tidak  menghadiri  kegiatan  yang  telah direncanakan,  termasuk  proses  pembelajaran  di kelas. '),
(25, 'Guru  menyelesaikan  semua  tugas  administratif dan  non‐pembelajaran  dengan  tepat  waktu  sesuai standar  yang  ditetapkan. '),
(25, 'Guru  memanfaatkan  waktu  luang  selain  mengajar untuk  kegiatan  yang  produktif  terkait  dengan tugasnya.'),
(25, 'Guru  memberikan  kontribusi  terhadap pengembangan  sekolah  dan  mempunyai  prestasi yang  berdampak  positif  terhadap  nama  baik sekolah. '),
(25, 'Guru  merasa  bangga  dengan  profesinya  sebagai guru. ');

INSERT INTO `questions` (`categorie_id`, `description`) VALUES
(26, 'Guru  memperlakukan  semua  peserta  didik  secara  adil, memberikan  perhatian  dan  bantuan  sesuai  kebutuhan masing‐masing,  tanpa  memperdulikan  faktor  personal. '),
(26, 'Guru  menjaga  hubungan  baik  dan  peduli  dengan teman  sejawat  (bersifat  inklusif),  serta  berkontribusi positif  terhadap  semua  diskusi  formal  dan  informal terkait  dengan  pekerjaannya. '),
(26, 'Guru  sering  berinteraksi  dengan  peserta  didik  dan tidak  membatasi  perhatiannya  hanya  pada  kelompok tertentu  (misalnya:  peserta  didik  yang  pandai,  kaya, berasal  dari  daerah  yang  sama  dengan  guru).'),
(27, 'Guru  menyampaikan  informasi  tentang  kemajuan, kesulitan,  dan  potensi  peserta  didik  kepada  orang tuanya,  baik  dalam  pertemuan  formal  maupun  tidak formal  antara  guru  dan  orang  tua,  teman  sejawat, dan  dapat  menunjukkan  buktinya.'),
(27, 'Guru  ikut  berperan  aktif  dalam  kegiatan  di  luar pembelajaran  yang  diselenggarakan  oleh  sekolah  dan masyarakat  dan  dapat  memberikan  bukti keikutsertaannya.'),
(27, 'Guru  memperhatikan  sekolah  sebagai  bagian  dari masyarakat,  berkomunikasi  dengan  masyarakat sekitar,  serta  berperan  dalam  kegiatan  sosial  di masyarakat.'),
(28, 'Guru  melakukan  pemetaan  standar  kompetensi dan  kompetensi  dasar  untuk  mata  pelajaran  yang diampunya,  untuk  mengidentifikasi  materi pembelajaran  yang  dianggap  sulit,  melakukan perencanaan  dan  pelaksanaan  pembelajaran,  dan memperkirakan  alokasi  waktu  yang  diperlukan.'),
(28, 'Guru  menyertakan  informasi  yang  tepat  dan mutakhir  di  dalam  perencanaan  dan  pelaksanaan pembelajaran.'),
(28, 'Guru  menyusun  materi,  perencanaan  dan pelaksanaan  pembelajaran  yang  berisi  informasi yang  tepat,  mutakhir,  dan  yang  membantu  peserta didik  untuk  memahami  konsep  materi pembelajaran.'),
(29, 'Guru  melakukan  evaluasi  diri  secara  spesifik, lengkap,  dan   didukung  dengan  contoh  pengalaman diri  sendiri.'),
(29, 'Guru  memiliki  jurnal  pembelajaran,  catatan  masukan dari  kolega  atau  hasil  penilaian  proses  pembelajaran sebagai  bukti  yang  menggambarkan  kinerjanya.'),
(29, 'Guru  memanfaatkan  bukti  gambaran  kinerjanya untuk  mengembangkan   perencanaan  dan pelaksanaan  pembelajaran  selanjutnya  dalam program  Pengembangan  Keprofesian  Berkelanjutan (PKB).'),
(29, 'Guru  dapat  mengaplikasikan  pengalaman  PKB  dalam perencanaan,  pelaksanaan,  penilaian  pembelajaran dan  tindak  lanjutnya.'),
(29, 'Guru  melakukan  penelitian,  mengembangkan  karya inovasi,  mengikuti  kegiatan  ilmiah  (misalnya  seminar, konferensi),  dan  aktif  dalam  melaksanakan  PKB.'),
(29, 'Guru  dapat  memanfaatkan  TIK  dalam  berkomunikasi dan  pelaksanaan  PKB.');
(30, 'Guru Selalu Hadir di sekolah di hari efektif pembelajaran'),
(30, 'Guru Selalu datang dan pulang mengajar di sekolah tepat waktu'),
(30, 'Guru patuh terhadap segala tata tertib yang berlaku di sekolah'),
(31, 'Guru selalu mendukung penuh kebijakan-kebijakan yang ditetapkan oleh lembaga (misal kebijakan pengelolaan keuangan dan sistem pendidikan)'),
(31, 'Guru memiliki rasa cinta dan rasa turut ikut memiliki yang tinggi terhadap lembaga tempat dia mengabdi'),
(31, 'Guru selalu siap menerima amanah yang diberikan oleh lembaga dan menjalankannya dengan penuh tanggung jawab'),
(31, 'Guru selalu terlibat aktif dalam upaya pengembangan lembaga'),
(31, 'Guru berperan aktif dalam menjaga nama baik lembaga, dan tidak menyebarkan informasi negatif tentang lembaga kepada pihak lain');

INSERT INTO `questions` (`categorie_id`, `description`) VALUES
(7, 'Guru mentaati peraturan yang berlaku di sekolah.'),
(7, 'Guru bekerja sesuai jadwal yang ditetapkan.'),
(7, 'Guru berpakaian rapi dan/atau sopan.'),
(7, 'Guru  rajin mengikuti kegiatan-kegiatan di sekolah'),
(7, 'Guru berperilaku baik terhadap saya dan guru lain.')
(7, 'Guru bersedia menerima kritik dan saran dari saya atau guru lain.'),
(8, 'Guru bersikap ramah kepada saya atau orang lain.'),
(8, 'Guru berbahasa santun kepada saya atau orang lain.'),
(8, 'Guru memberi motivasi kepada saya atau teman-teman guru lain.'),
(8, 'Guru pandai berkomunikasi secara lisan atau tertulis.'),
(8, 'Guru memotivasi diri dan rekan sejawat secara aktif dan kreatif dalam melaksanakan proses pendidikan.'),
(9, 'Guru memiliki kretivitas dalam pembelajaran.'),
(9, 'Guru  memiliki pengetahuan dan keterampilan Teknologi Informasi (TI) yang memadai.'),
(9, 'Guru memiliki perangkat pembelajaran yang lengkap.'),
(9, 'Guru ada di sekolah meskipun  tidak mengajar di kelas.'),
(9, 'Guru memulai  pembelajaran tepat waktu.'),
(10, 'Guru memberitahukan perkembangan belajar putra/putri saya.'),
(10, 'Guru  memberi kesempatan berkomunikasi dengan saya yang berkaitan dengan perilaku atau kesulitan belajar.'),
(10, 'Guru bekerja sama dengan orang tua untuk menyelesaikan kesulitan belajar putra/putri saya.'),
(11, 'Guru berperan sebagai orang tua bagi putra/putri saya di sekolah.'),
(11, 'Guru mengubah perilaku putra/putri saya menjadi lebih baik.'),
(11, 'Guru memberikan bimbingan dalam pembelajaran kepada putra/putri saya yang dapat dimanfaatkan dalam kehidupan sehari-hari.'),
(11, 'Guru disenangi oleh putra/putri saya dan teman-temannya.'),
(11, 'Guru mengembalikan hasil belajar (PR, tugas, hasil ulangan)  putra/putri saya dilengkapi dengan catatan.'),
(12, 'Guru menyampaikan materi pelajaran dengan contoh dalam kehidupan sehari-hari.'),
(12, 'Guru  menjelaskan materi pelajaran  dari buku paket dan sumber belajar lainnya.'),
(12, 'Guru memberikan contoh atau permasalahan yang berhubungan dengan keadaan saat ini.'),
(12, 'Guru  menjawab pertanyaan dengan jelas.'),
(12, 'Guru  menjawab pertanyaan dengan benar.'),
(13, 'Guru menyampaikan kegiatan yang akan dilakukan selama pembelajaran.'),
(13, 'Guru  memberikan motivasi kepada  saya dan teman-teman.'),
(13, 'Guru menyampaikan materi pelajaran dengan mudah dimengerti.'),
(13, 'Guru  mengajar dengan cara yang bervariasi misalnya diskusi, demonstrasi, tanya jawab, ceramah, dll.'),
(13, 'Guru  berbicara dengan jelas ketika menyampaikan materi pelajaran.'),
(14, 'Guru mengajak  saya dan teman-teman untuk berperilaku baik.'),
(14, 'Guru  memberi contoh perilaku yang sesuai aturan.'),
(14, 'Guru  menjalankan ibadah saat di sekolah'),
(14, 'Guru   berpakaian rapi sesuai aturan sekolah.'),
(14, 'Guru menghargai perbedaan asal, suku, ras dan agama.'),
(15, 'Guru  memperhatikan kebutuhan belajar  saya dan teman-teman.'),
(15, 'Guru  menyebutkan nama  saya dan teman-teman selama kegiatan pembelajaran atau  kegiatan lainnya)'),
(15, 'Guru  memberi perhatian kepada  saya dan temanteman.'),
(15, 'Guru  memilihara komunikasi yang baik dengan semua peserta didik.'),
(15, 'Guru  mudah dihubungi pada saat diperlukan untuk diskusi. ');

